# How to use MeanDecreaseImpurity class

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier, ExtraTreeClassifier
from sklearn.ensemble import (RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier,
                              GradientBoostingClassifier, IsolationForest)

from eml.importances.mdi import MeanDecreaseImpurity

In [3]:
iris = load_iris()

In [42]:
mdi = MeanDecreaseImpurity(features=iris.feature_names, use_precompute=False)

estimators = (DecisionTreeClassifier(), ExtraTreeClassifier(),
              RandomForestClassifier(), AdaBoostClassifier(),
              ExtraTreesClassifier(), GradientBoostingClassifier())

for e in estimators:
    e.fit(iris.data, iris.target)
    try:
        importances = mdi.predict(e)
    except Exception as err:
        print(type(e))
        raise err
    np.testing.assert_allclose(importances, e.feature_importances_)

In [39]:
gbe = GradientBoostingClassifier()
gbe.fit(iris.data, iris.target)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [34]:
mdi = MeanDecreaseImpurity(features=iris.feature_names, use_precompute=False)
mdi.predict(gbe)

array([0.00797822, 0.0102907 , 0.23532202, 0.74640906])

In [35]:
gbe.feature_importances_

array([0.00797822, 0.0102907 , 0.23532202, 0.74640906])

In [13]:
e.estimators_[0][0].tree_.n_leaves

2

In [112]:
mdi.predict(forest, weighted=True)

array([0.11030335, 0.02928489, 0.45879072, 0.40162104])

In [113]:
forest.feature_importances_

array([0.11030335, 0.02928489, 0.45879072, 0.40162104])

In [114]:
mdi.predict(tree, weighted=True)

array([0.02666667, 0.        , 0.05072262, 0.92261071])

In [115]:
tree.feature_importances_

array([0.02666667, 0.        , 0.05072262, 0.92261071])